### PR TITLE
stop() method

### PR DESCRIPTION
**Pull request by timwilson235**
I think this is what you wanted to see. Hope I did everything right, I'm new to using github.

### CODE REVIEW

**Comment by alextaujenis** [comment]
Thanks Tim, this looks great! I merged these changes into [Timer v1.1.0](https://github.com/alextaujenis/RBD_Timer/releases/tag/1.1.0).

**Comment by timwilson235** [comment]
Good...

I should mention, just FYI: in my code I initialized _state in the
constructor init list, rather than in the class def in the header. You
changed that back, to initialize _state in the header:

```
  enum {ACTIVE, EXPIRED, STOPPED} _state = EXPIRED;  // timer internal
```

state

The reason I had done it in the constructor init list (the old-fashioned
way) was to eliminate a compile warning:

In file included from unit_test.ino:7:0:
/Users/twilson/Documents/Arduino/libraries/RBD_Timer/src/RBD_Timer.h:33:48:
warning: non-static data member initializers only available with -std=c++11
or -std=gnu++11 [enabled by default]
       enum {ACTIVE, EXPIRED, STOPPED} _state = EXPIRED;  // timer internal
state

Kind of a silly warning, since it's saying that it's legal under the
default compiler config. But I hate spurious warnings since they can make
you overlook significant warnings!

It is true that this style of init is a relatively new addition to c++.
Also, for some reason it doesn't warn about the other similar inits (e.g.
_has_been_active, _has_been_expired) - I don't know why.

Do you get this warning? Perhaps there's some way I can reconfig my Arduino
IDE so that I don't get this warning?

On Mon, Nov 23, 2015 at 6:37 AM, Alex Taujenis notifications@github.com
wrote:

> Thanks Tim, this looks great! I merged these changes into the new Timer
> v1.1.0 https://github.com/alextaujenis/RBD_Timer/releases/tag/1.1.0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alextaujenis/RBD_Timer/pull/2#issuecomment-158934941.

## 

"If I have not seen as far as other men, it is because giants have stood on
my shoulders"

**Comment by alextaujenis** [comment]
Try upgrading to Arduino IDE 1.6.6. I don't see this compiler warning when using the latest version.

**Comment by timwilson235** [comment]
Yep, that fixes it.

On Mon, Nov 23, 2015 at 12:02 PM, Alex Taujenis notifications@github.com
wrote:

> Try upgrading to Arduino IDE 1.6.6. I don't see this compiler warning.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alextaujenis/RBD_Timer/pull/2#issuecomment-159028974.

## 

"If I have not seen as far as other men, it is because giants have stood on
my shoulders"

**Pull request merged**
